[project]
name = "quickstarter-mcp-server"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Youjun Go", email = "youjun.go@sk.com" }
]
requires-python = ">=3.12"
dependencies = [
    "build>=1.3.0",
    "mcp>=1.12.3",
    "twine>=6.1.0",
]

[project.scripts]
quickstarter-mcp-server = "quickstarter_mcp_server:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
