[project]
name = "just-focus"
version = "0.2.2"
description = "Vector electromagnetic field calculations in the focus of high NA microscope objectives."
readme = "README.md"
license = "GPL-3.0-or-later"
authors = [
    { name = "Kyle Douglass", email = "kyle.douglass@epfl.ch" }
]
requires-python = ">=3.11"

dependencies = [
    "numpy>=2.3.2",
]

[project.optional-dependencies]
plot = [
    "matplotlib>=3.10.5",
    "pyside6>=6.9.1",
]

[project.scripts]
gaussian = "leb.just_focus.scripts.gaussian:main"
halfmoon = "leb.just_focus.scripts.halfmoon:main"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/leb"]
