[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "logwise"
version = "1.4.0"
description = "A clean, colorful terminal logger with boxed message support."
readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
license = { file = "LICENSE" }

authors = [
  { name = "Prateek Gupta", email = "prateekgupta1089@gmail.com" }
]

dependencies = [
  "wcwidth>=0.2.6"
]

classifiers = [
  "Programming Language :: Python :: 3",
  "License :: OSI Approved :: MIT License",
  "Operating System :: OS Independent"
]

[tool.setuptools.packages.find]
where = ["."]