[build-system]
requires = ["setuptools>=69.5", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name            = "drvd-bench"
version         = "0.2.2"
description     = "Benchmark toolkit for DrVD"
readme          = "README.md"
license         = {file = "LICENSE"}
authors         = [
  {name = "Yin Xu", email = "xuyin23@mails.tsinghua.edu.cn"}
]
requires-python = ">=3.9"
dependencies    = [
  "bert-score",
  "tqdm",
  "nltk",
  "openai",
  "Pillow",
  "torch",
  "transformers",
]

[project.urls]
Homepage = "https://github.com/Jerry-Boss/DrVD-Bench"
Issues   = "https://github.com/Jerry-Boss/DrVD-Bench/issues"

[tool.setuptools.package-data]
# 将 jupyter 文件一起打包
"drvd_bench" = ["*.ipynb"]