[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "hexgrid_cube"
version = "0.4.2"
authors = [
    {name="Quentin Dimarellis", email="qdimarellis@laposte.net"}
]
description = "Hex grid utilities using cube coordinates"
readme = "README.md"
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "CC-BY-4.0"
license-files = ["LICENSE"]

[project.urls]
Homepage = "https://gitlab.com/loldebyte/hexgrid_cube"
Issues = "https://gitlab.com/loldebyte/hexgrid_cube/-/issues"
