[build-system]
requires = ["hatchling >= 1.26"]
build-backend = "hatchling.build"

[project]
name = "logcatter"
version = "0.3.3"
authors = [
  { name="KANG SAN", email="san.kang@rivmt.com" },
]
description = "Logcat style log library"
readme = "README.md"
requires-python = ">=3.7"
classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: OS Independent",
]
license = "MIT"
license-files = ["LICEN[CS]E*"]

[project.urls]
Homepage = "https://github.com/RivMt/logcatter"
Issues = "https://github.com/RivMt/logcatter/issues"