[build-system]
requires = ["setuptools >= 80.1.0"]
build-backend = "setuptools.build_meta"

[project]
name = "net_kusto_client"
version = "0.1.2"
description = "A Kusto client package"
readme = "README.md"
requires-python = ">=3.9"
authors = [
  { name="Larry Zhu", email="larry.lan.zhu@gmail.com" },
]
license = "MIT"
dependencies = [
  "azure-kusto-data>=5.0.3",
  "azure-kusto-ingest>=5.0.3",
  "pandas>=2.3.0",
  "aiohttp>=3.12.13"
]
keywords = ["network", "kusto", "client"]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "Operating System :: OS Independent",
]

[project.urls]
Repository = "https://github.com/myusernamehasbeentaken/net-kusto-client"

[tool.setuptools.packages.find]
where = ["src"]
include = ["net_kusto_client"]

[tool.setuptools]
include-package-data = true

[tool.setuptools.package-data]
"net_kusto_client" = ["*.csv", "*.json"]
