[build-system]
requires = ["setuptools>=61.0", "wheel", "pillow<=11.3.0"]
build-backend = "setuptools.build_meta"

[project]
name = "captcha_jnrtor"
version = "2.0.0"
description = "This is a python-package meant to create automatic captcha"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [{name = "UndrDsk0M", email = "its1.ehsan@gmail.com"}]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.urls]
Homepage = "https://github.com/UndrDsk0M/captcha_generator"
