[tool.poetry]
name = "py-aioclient"
version = "0.1.6"
description = "Um cliente HTTP assíncrono e leve para Python, com uma API simplificada para requisições fáceis e concorrentes."
license = "MIT"
authors = ["Abel Salim <abelsalim@proton.me>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.10"
aiohttp = "^3.12.13"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
