[project]
name = "just-focus"
version = "0.3.0"
description = "Vector electromagnetic field calculations in the focus of high NA microscope objectives."
readme = "README.md"
license = "GPL-3.0-or-later"
authors = [
    { name = "Kyle Douglass", email = "kyle.douglass@epfl.ch" }
]
keywords = ["microscopy", "electromagnetism", "richards-wolf", "diffraction"]
classifiers = [
  # How mature is this project? Common values are
  #   3 - Alpha
  #   4 - Beta
  #   5 - Production/Stable
  "Development Status :: 4 - Beta",

  "Intended Audience :: Science/Research",
  "Topic :: Scientific/Engineering :: Physics",

  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: 3.13",
]
requires-python = ">=3.11"

dependencies = [
    "numpy>=2.3.2",
]

[project.optional-dependencies]
plot = [
    "matplotlib>=3.10.5",
    "pyside6>=6.9.1",
]

[project.scripts]
gaussian = "leb.just_focus.scripts.gaussian:main"
halfmoon = "leb.just_focus.scripts.halfmoon:main"

[dependency-groups]
dev = [
    "pytest>=8.4.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/leb"]
