[project]
name = "mpsapi"
version = "0.0.8"
description = "Асинхронные клиенты для маркетплейсов"
readme = "README.md"
authors = [
    { name = "Dmitry Drozdov", email = "ds.drozdov@gmail.com" }
]
requires-python = ">=3.13"
dependencies = [
    "aiohttp>=3.12.13",
]

[project.scripts]
mpsapi = "mpsapi:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "aioresponses>=0.7.8",
    "loguru>=0.7.3",
    "mypy>=1.17.0",
    "notebook>=7.4.4",
    "pydantic>=2.11.7",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "python-box>=7.3.2",
    "python-dotenv>=1.1.1",
    "pyyaml>=6.0.2",
    "requests>=2.32.4",
]
