# Development dependencies
[tool.poetry.group.dev.dependencies]
pytest = "^8.0"

[build-system]
requires = ["setuptools>=65.5.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pluk"
version = "0.0.1"
description = "Symbol lookup / search engine CLI"
readme = "README.md"
requires-python = ">=3.13.5"
license = { text = "MIT" }
authors = [
  { name = "Justus Jones", email = "Justus1274@gmail.com" }
]
keywords = ["symbol","search","cli","index","lookup"]

[tool.setuptools]
package-dir = {"" = "src"}


[project.scripts]
pluk = "pluk.cli:main"
