[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "dispozitsi"
dynamic = ["version"]
description = "Debugger tool for Logstash's Grok parsing language."
readme = "README.md"
requires-python = ">=3.11"
license = "GPL-3.0-or-later"
keywords = ["Grok", "Debugger", "Textualize", "TUI"]
authors = [
  { name = "spuzkov", email = "spuzkov@noreply.codeberg.org" },
]
classifiers = [
  "Development Status :: 4 - Beta",
  "Environment :: Console",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
  "textual[syntax]==5.2.0",
  "textual-dev==1.7.0",
]

[project.scripts]
dispozitsi = "dispozitsi.entry_points:dispozitsi"

[project.urls]
Documentation = "https://codeberg.org/spuzkov/dispozitsi#readme"
Issues = "https://codeberg.org/spuzkov/dispozitsi/issues"
Source = "https://codeberg.org/spuzkov/dispozitsi"

[tool.hatch.version]
path = "src/dispozitsi/__about__.py"

[tool.coverage.run]
source_pkgs = ["dispozitsi", "tests"]
branch = true
parallel = true
omit = [
  "src/dispozitsi/__about__.py",
]

[tool.coverage.paths]
dispozitsi = ["src/dispozitsi", "*/dispozitsi/src/dispozitsi"]
tests = ["tests", "*/dispozitsi/tests"]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
