[project]
name = "turbovault4dbt"
version = "0.1.0"
description = "CLI for Turbovault 4 DBT"
authors = [
    { name = "Pawel", email = "pawel.sala01@wp.pl" }
]
readme = "README.md"
requires-python = ">=3.8"
license = "Apache-2.0"
dependencies = [
        "asn1crypto",        "cachetools",        "certifi",        "cffi",        "charset-normalizer",        "cryptography",        "db-dtypes",        "et_xmlfile",        "filelock",        "google-api-core",        "google-auth",        "google-auth-oauthlib",        "google-cloud-bigquery",        "google-cloud-core",        "google-crc32c",        "google-resumable-media",        "googleapis-common-protos",        "grpcio",        "grpcio-status",        "gspread",        "idna",        "numpy",        "oauthlib",        "openpyxl",        "packaging",        "pandas",        "platformdirs",        "proto-plus",        "protobuf",        "pyarrow",        "pyasn1",        "pyasn1_modules",        "pycparser",        "PyJWT",        "pyOpenSSL",        "python-dateutil",        "pytz",        "requests",        "requests-oauthlib",        "rsa",        "six",        "snowflake-connector-python",        "sortedcontainers",        "tomlkit",        "typing_extensions",        "tzdata",        "urllib3",        "networkx",]

[project.scripts]
turbovault = "turbovault4dbt.main:main"

[tool.setuptools]
package-dir = {"" = "src"}

