[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "fady"
version = "0.0.0"
authors = [
    { name = "Fady", email = "contact@fadymohamed.com" },
]
description = "A micro-framework for building with LLMs, inspired by LangChain."
readme = "README.md"
license = { file = "LICENSE" }
requires-python = ">=3.6"
dependencies = [
    "pydantic>=2.0",
    "jinja2>=3.0",
    "openai>=1.0",
    "python-dotenv",
]

[project.optional-dependencies]
local = [
    "faiss-cpu>=1.7.4,<1.12",  # stable range, avoids mismatch with NumPy 2.x
    "numpy>=1.22,<2.0",        # prevent deprecation warnings
    
]
gpu = [
    "faiss-gpu>=1.7.4,<1.12",
    "numpy>=1.22,<2.0",
]
azure = [
    "azure-search-documents",
    "azure-core",
  
]
token_splitter = [
    "tiktoken>=0.5.0"
]

# An 'all' extra is a common convention to install everything.
all = [
    "minichain-ai[local]",
    "minichain-ai[azure]",
    "minichain-ai[token_splitter]"
  
]

[project.urls]
Homepage = "https://github.com/fady17/minichain"
Issues = "https://github.com/fady17/minichain/issues"