[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "anondrop"
version = "0.2.0"
description = "A package for uploading and deleting files using AnonDrop API"
readme = "README.md"
license = {text = "MIT"}
authors = [{name = "BubblePlayz", email = "mylaptop4768@gmail.com"}]
keywords = ["anondrop", "upload", "delete", "files"]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "requests>=2.25.1"
]
requires-python = ">=3.6"