[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "vulnscan"
version = "3.2.0"
authors = [
  { name="Gokul Kannan G", email="gokulkannan.dev@gmail.com" },
]
description = "A vulnerability scanner"
readme = "README.md"
requires-python = ">=3.7, <3.14"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
dependencies = [
    "selenium",
    "tqdm",
    "reportlab",
    "python-nmap",
    "colorama",
    "fuzzywuzzy",
    "python-Levenshtein",
    "cryptography",
    "progress",
    "python-dotenv",
    "tensorflow",
    "keras",
    "scikit-learn",
    "numpy",
    "pandas",
    "boto3",
    "google-cloud-storage",
    "azure-storage-blob",
    "kubernetes",
    "graphql-core",
    "requests-toolbelt",
    "matplotlib",
    "seaborn",
    "plotly",
    "dnspython",
    "html5lib",
    "chardet",
    "playwright",
    "uvloop",
    "jinja2",
    "weasyprint",
    "joblib",
    "h5py",
    "openapi-spec-validator",
    "dotenv",
    "beautifulsoup4",
]

[project.scripts]
vulnscan = "vulnscan.cli:main"

[project.urls]
"Homepage" = "https://github.com/iamgokulkannan/vulnscan"
"Bug Tracker" = "https://github.com/iamgokulkannan/vulnscan/issues"

[tool.setuptools.packages.find]
where = ["."]
include = ["vulnscan*"]