[project]
name = "dockerz"
version = "1.0.4"
description = "A CLI tool to build and push multiple Docker images in parallel."
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "click>=8.1.0",
    "pyyaml>=6.0"
]

[project.scripts]
dockerz = "dockerz.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["dockerz"]
