[project]
name = "abs-nosql-charts-core"
version = "0.1.8"
description = "A dashboard core library that provide all dashboard related base classes and utilities"
authors = [
    {name = "divy551",email = "divydedakiya5@gmail.com"}
]
readme = "README.md"
requires-python = ">=3.13,<4.0"
dependencies = [
    "abs-nosql-repository-core (>=0.9.5,<0.10.0)",
]


[tool.poetry]
packages = [{include = "abs_nosql_charts_core"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
