[project]
name="glassInit"
version="0.0.4"
authors=[{name="Psyche Halo", email="Psyche@WinsGod.com"},]
description="glassInit is a way to initialize the parameters of a neural network layer @pytorch. It is suitable for shortcut connections where tensor sizes need to be adjusted. The flow of information between forward and backward propagation is maximized while adjusting the tensor size. "
readme = "README.md"
requires-python=">=3.8"
classifiers=["Programming Language :: Python :: 3", "Operating System :: OS Independent",]
dependencies=["torch >= 1.7.0",]
keywords = ["glassInit", "initialize", "shortcut", "PyTorch", "AI", "neural", "NN", "connections","Skip Connections", "Res",]
[project.urls]
Homepage="https://github.com/PsycheHalo/glassInit"
Issues="https://github.com/PsycheHalo/glassInit/issues"
[metadata]
license_expression = "MPL-2.0"
