[project]
name = "pythagix"

version = "0.2.16"
description = "A mathy Python package with utilities like LCM, triangle numbers, etc."
readme = "README.md"
requires-python = ">=3.6"
authors = [
    { name = "UltraQuantumScriptor" }
]
license = { text = "MIT" }
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License"
]
dependencies = []
keywords = ["math", "prime", "LCM", "triangle numbers", "gcd", "statistics", "utilities"]
urls = { "Homepage" = "https://github.com/UltraQuantumScriptor/pythagix", "Source" = "https://github.com/UltraQuantumScriptor/pythagix", "Bug Tracker" = "https://github.com/UltraQuantumScriptor/pythagix/issues" }

