[project]
name = "pdbsharp"
version = "0.1.1"
description = "A TUI frontend for pdb"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "textual>=5.2.0",
]
classifiers = [
    "Development Status :: 2 - Pre-Alpha",
    "Environment :: Console",
    "Topic :: Software Development :: Debuggers"
]

[project.urls]
Repository = "https://github.com/JeffersGlass/pdbsharp.git"
Issues = "https://github.com/JeffersGlass/pdbsharp.issues"


[dependency-groups]
dev = [
    "pre-commit>=4.2.0",
    "pytest>=8.4.1",
    "pytest-asyncio>=1.0.0",
    "pytest-timeout>=2.4.0",
    "textual-dev>=1.7.0",
]

[project.scripts]
pdbsharp = "pdbsharp.pdbsharp:main"
dummy = "pdbsharp.dummy:dummy"

[tool.pytest.ini_options]
pythonpath = "src/"
asyncio_mode = "auto"

[[tool.uv.index]]
name = "pypi"
url = "https://pypi.org/simple/"
publish-url = "https://pypi.org/legacy/"
explicit = true

[[tool.uv.index]]
name = "testpypi"
url = "https://test.pypi.org/simple/"
publish-url = "https://test.pypi.org/legacy/"
explicit = true

[build-system]
requires = ["uv_build"]
build-backend = "uv_build"
