[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "phoney"
version = "0.2.9"
description = "Fake Info generator, a library for generating realistic personal data like names, phone numbers, emails, and more."
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [{name = "rarfile", email = "d7276250@email.com"}]
homepage = "https://github.com/YTstyo/phoney"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]

[project.urls]
Homepage = "https://github.com/YTstyo/phoney"

[tool.flit.sdist]
include = ["phoney/data/**/*"]
