[build-system]
requires = [
  "setuptools>=61.0"
]
build-backend = "setuptools.build_meta"

[project]
name = "nadeo-api"
version = "0.7.0"
authors = [
  {name="Ezio416", email="e@e416.dev"},
]
description = "Access Nadeo's web services API and the public Trackmania API"
keywords = [
  "nadeo",
  "api",
  "trackmania"
]
readme = "README.md"
license = "MIT"
license-files = [
  "LICENSE.txt"
]
requires-python = ">=3.12"
classifiers = [
  "Programming Language :: Python :: 3",
  "Operating System :: OS Independent",
]
dependencies = [
  "requests >= 2.31.0"
]

[project.urls]
"Bug Tracker" = "https://github.com/ezio416/py-nadeo-api/issues"
"Documentation" = "https://nadeo-api.readthedocs.io/en/latest/"
"Repository" = "https://github.com/ezio416/py-nadeo-api"
