[build-system]
requires = ["setuptools>=59.0", "numpy>=1.21.2"]
build-backend = "setuptools.build_meta"

[project]
name = "crimm-dock"
version = "2025.8a1"
authors = [
  { name="Truman Xu", email="ziqiaoxu@umich.edu" },
]
description = "Docking Module for Chemistry with the ReInvented Macromolecular"
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "crimm",
    "scikit-learn"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: GNU General Public License v3 (GPLv3)",
    "Operating System :: OS Independent",
    "Development Status :: 2 - Pre-Alpha",
]

[project.urls]
"Homepage" = "https://github.com/Truman-Xu/crimm-dock"
"Bug Tracker" = "https://github.com/Truman-Xu/crimm-dock/issues"

[tool.setuptools.packages.find]
where = ["./"]
exclude = [
    "src", 
    "__pycache__", 
    ".ipynb_checkpoints", 
    "*.egg-info", 
    "tests"
]
namespaces = false