[tool.poetry]
name     = "OTF_General"
version  = "0.1.0"
packages = [
    { include = "otf_abfe", from = "src" },
    { include = "otf_rbfe", from = "src" }
]

[project]
name = "OTF_General"
version = "0.1.0"
description = "Alchemical binding freeâ€energy workflow"
authors = [
    {name = "S. Benjamin Koby and Maria G. Kurnikova"}
]
license = {text = "MIT"}
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "numpy (>=2.3.2,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
