[package]
name = "kryptoon"
version = "1.0.0"
edition = "2024"

authors = ["Anonymous <224859321+bitmolester@users.noreply.github.com>"]
description = "Python Cryptography"
keywords = ["python", "cryptography"]

license = "Unlicense"
readme = "readme.md"

homepage = "https://github.com/bitmolester/kryptoon"
documentation = "https://github.com/bitmolester/kryptoon"
repository = "https://github.com/bitmolester/kryptoon"

[lib]
crate-type = ["cdylib"]
path = "source/rust/library.rs"

[dependencies.pyo3]
version = "0.25.1"
features = ["extension-module"]

[dependencies.oqs]
version = "0.11.0"
default-features = false
features = ["sigs", "kems"]

[dependencies.argon2]
version = "0.5.3"

[dependencies.rand]
version = "0.8.0"

[dependencies.blake3]
version = "1.8.2"

[dependencies.bcrypt]
version = "0.17.0"

[dependencies.ripemd]
version = "0.1.3"

[dependencies.bs58]
version = "0.5.1"

[dependencies.sha3]
version = "0.10.8"

[profile.release]
overflow-checks = true
