[project]
name = "akashshare"
version = "0.1.3"
description = "CLI tool to share files over LAN using UDP + TCP"
authors = [
  { name="Akash", email="akashpawar202k@gmail.com" }
]
readme = "README.md"
license = {text = "MIT"}
requires-python = ">=3.8"

dependencies = [
  "InquirerPy",
]

[project.scripts]
akashshare = "akashshare.__main__:main"

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
