[project]
name = "speechcapture"
version = "0.2.0"
description = "An easy to use library for recording and saving speech audio"
authors = [
    {name = "Bilal Darwish", email = "darwish.b.bilal@gmail.com"}
]
license = {file = "LICENSE"}
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyaudio (>=0.2.14,<0.3.0)",
    "numpy (>=2.3.2,<3.0.0)"
]
keywords = ["speech", "audio", "record"]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"