[project]
name = "spai"
version = "2025.08.04"
description = ""
authors = [{name = "Jan Sensio", email = "it@earthpulse.es"}]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "bson>=0.5.10",
    "minio>=7.1.15",
    "pandas>=2.0.2",
    "pillow>=10.2.0",
    "pydantic>=2.0.3",
    "pyjwt>=2.7.0",
    "python-dotenv>=1.0.1",
    "pyyaml>=6.0.0",
    "requests>=2.31.0",
    "rich>=13.7.0",
    "schedule>=1.2.0",
    "typer>=0.9.0",
]

[project.scripts]
spai = "spai.cli:app"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["spai"]
