[project]
name = "mcp-agents-mytool"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "httpx>=0.28.1",
    "mcp[cli]>=1.12.3",
    "numpy>=2.3.2",
]

[project.scripts]
mcp-agents-mytool = "main:main"