[tool.poetry]
name = "pupeyes"
version = "0.3.7"
description = "PupEyes: Your Buddy for Pupil Size and Eye Movement Data Analysis"
authors = ["Han Zhang"]
license = "GNU General Public License v3.0"
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.10.16,<4.0"
pandas = "^2.2.3"
tqdm = "^4.67.1"
intervaltree = "^3.1.0"
opencv-python-headless = "^4.4.0.46"
scipy = "^1.15.2"
seaborn = "^0.13.2"
pillow = "^11.1.0"
dash = "^2.18.2"
dash-bootstrap-components = "^1.7.1"
nbformat = "^5.10.4"
dill = "^0.3.9"
ipywidgets = "^8.1.5"
h5py = "^3.14.0"
tables = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
