[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "sir3stoolkit"
version = "90.15.1.dev2"
description = "SIR3S Toolkit"
authors = [
    { name="3S Consult GmbH", email="sir3stoolkit@3sconsult.de" }
]
readme = "README.rst"
license = { text = "MIT" }  # oder "Proprietary", wenn intern
requires-python = ">=3.12"
keywords = ["Python", "3S", "SIR 3S", "SirGraf", "SirCalc", "3S Consult"]
dependencies = [
    "numpy",
    "pythonnet",
]

[project.urls]
Documentation = "https://3sconsult.github.io/sir3stoolkit"
Source = "https://github.com/3SConsult/sir3stoolkit"

[project.optional-dependencies]
dev = [
    "pytest",
    "flake8",
    "build",
    "twine",
    "sphinx",
    "sphinx_rtd_theme",
]

sphinx = [
    "nbsphinx",
    "sphinx_copybutton",
    "sphinx_togglebutton"
]

[tool.setuptools.packages.find]
where = ["src"]
