[project]
name = "fletft"
version = "0.0.5"
description = "Flet add .ft and screen menager"
authors = [{ name = "Przemek", email = "email@example.com" }]

readme = { file = "README.md", content-type = "text/markdown" }
requires-python = ">=3.8"
dependencies = [
    "flet",
    "PyYAML",
]

[tool.setuptools.packages.find]
where = ["."]
include = ["flet_ft*"]

[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"
