[project]
name = "deltaapply"
version = "0.0.2"
description = "Change Data Capture und Anwendung von Inserts, Updates und Deletes"
readme = "README.md"
requires-python = ">=3.12"
license = { text = "MIT"}
dependencies = [
    "pandas>=2.3.1",
    "polars>=1.32.0",
    "pyarrow>=21.0.0",
    "sqlalchemy>=2.0.42",
]

[dependency-groups]
dev = [
    "pytest>=8.4.1",
    "pytest-cov>=6.2.1",
]
