[build-system]
requires = ["setuptools>=42", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "revenium-middleware-litellm"
version = "0.1.28"
description = "A Python library that meters LiteLLM usage to Revenium."
readme = "README.md"
requires-python = ">=3.8"
license = "MIT"
authors = [
    { name = "Revenium", email = "info@revenium.io" }
]
dependencies = [
    "wrapt",
    "revenium_middleware",
    "litellm",
]
keywords = ["litellm", "middleware", "logging", "token-usage", "metering", "revenium"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Operating System :: OS Independent",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Libraries :: Python Modules"
]

[project.urls]
"Homepage" = "https://github.com/revenium/revenium-middleware-litellm-python"
"Bug Tracker" = "https://github.com/revenium/revenium-middleware-litellm-python/issues"
"Documentation" = "https://github.com/revenium/revenium-middleware-litellm-python/blob/main/README.md"

[project.optional-dependencies]
litellm_proxy = [
    "litellm[proxy]",
    "revenium_middleware>=0.3.4"
]
litellm_client = [
    "litellm",
    "wrapt",
    "revenium_middleware>=0.3.4"
]

litellm_all = [
    "litellm[proxy]",
    "litellm",
    "wrapt",
    "revenium_middleware>=0.3.4"
]

# Add setuptools specific configuration here
[tool.setuptools]
packages = ["revenium_middleware_litellm_client", "revenium_middleware_litellm_proxy"]
