# pyproject.toml
[build-system]
requires = ["setuptools>=61.0.0"]
build-backend = "setuptools.build_meta"

[project]
name = "devbrain"
version = "1.1.8"
authors = [{ name = "Anton", email = "anton@mimecam.com" }]
description = "A FastMCP server for DevBrain stdio communication."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
requires-python = ">=3.10"
classifiers = [
    "Programming Language :: Python :: 3.10",
    "Operating System :: OS Independent",
    'Intended Audience :: Developers',
]
dependencies = ["fastmcp", "requests"]

[project.urls]
Homepage = "https://github.com/mimeCam/mcp-devbrain-stdio"
"Bug Tracker" = "https://github.com/mimeCam/mcp-devbrain-stdio/discussions"

[project.scripts]
devbrain-stdio-server = "mcp_server.server:main" # NOTE: - this should not include `src.` prefix. Otherwise this error is triggered: `from src.mcp_server.server import main. ModuleNotFoundError: No module named 'src'`
