[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "BDviz"
version = "0.0.3"

dependencies = [
 "numpy","astropy", "matplotlib", "astroquery", "ipympl"
]
