[build-system]
requires = [
  "setuptools>=61",
  "setuptools_scm"
]
build-backend = "setuptools.build_meta"

[project]
name = "xflow-py"
dynamic = ["version"]       
description = "A modular ML framework for training and evaluation tasks"
authors = [{ name = "Qiyuan Xu" }]
license = { file = "LICENSE" }
readme = "README.md"
requires-python = ">=3.8"
keywords = ["machine-learning", "tensorflow", "data-pipeline"]
dependencies = [
    "numpy",
    "matplotlib",
    "opencv-python",
    "tqdm",
    "pydantic",
    "typing-extensions>=4.0.0",  
]

urls = { Homepage = "https://github.com/Andrew-XQY/XFlow"}

classifiers = [
  "License :: OSI Approved :: MIT License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.12",
  "Topic :: Scientific/Engineering :: Artificial Intelligence",
]


[project.optional-dependencies]
dev = [
    "tensorflow==2.16.2",  
    "keras==3.4.1",  
    "mypy",
    "pre-commit",
    "black",
    "isort",
]
docs = ["sphinx", "sphinx-rtd-theme"]

[tool.setuptools]
package-dir = { "" = "src" }

[tool.setuptools.packages.find]
where = ["src"]
exclude = [
    "xflow.extensions",
    "xflow.extensions.*"
]  # Exclude extensions from distribution

[tool.setuptools_scm]
version_scheme = "post-release"    # (optionalâ€”defaults are fine)
local_scheme   = "no-local-version"
write_to       = "src/xflow/_version.py"
tag_regex      = "^v(?P<version>.*)$"

# Black configuration
[tool.black]
line-length = 88
target-version = ['py312']
include = '\.pyi?$'
extend-exclude = '''
# A regex preceded by a single or double quote
/(
  # directories
  \.eggs
  | \.git
  | \.mypy_cache
  | \.tox
  | \.venv
  | build
  | dist
  | docs
)/
'''

# isort configuration
[tool.isort]
profile = "black"
multi_line_output = 3
line_length = 88
known_first_party = ["xflow"]
src_paths = ["src", "tests"]
skip_glob = ["docs/*"]
