[project]
name = "pyrl-complete"
version = "0.1.3"
description = "manage readline autocomplete for bespoke cli"
authors = [
    {name = "codimoc",email = "codimoc@prismoid.uk"}
]
readme = "README.md"
license = "GNU AFFERO GENERAL PUBLIC LICENSE Version 3"
requires-python = ">=3.9"
dependencies = [
    "ply (>=3.11,<4.0)"
]
keywords = ["readline", "autocomplete", "cli", "ply"]

[project.urls]
repository = "https://github.com/codimoc/pyrl-complete"

[project.scripts]
pyrl_rules_tester = "pyrl_complete.apps.tester:main"

[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.group.test.dependencies]  
pytest = "^8.4.0"  
